import React, { useRef } from "react";
import { Download, Share2, Mail, MessageSquare } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import { toast } from "sonner";

interface ExportActionsProps {
  contentRef: React.RefObject<HTMLDivElement>;
  prescriptionData: any;
}

const ExportActions = ({ contentRef, prescriptionData }: ExportActionsProps) => {
  const handleExportPDF = async () => {
    if (!contentRef.current) return;

    try {
      toast.loading("Generating PDF report...");
      
      const element = contentRef.current;
      
      // Temporary style changes to capture full content if scrolled
      const originalStyle = element.style.cssText;
      const tables = element.querySelectorAll('.overflow-x-auto');
      const originalTableStyles: string[] = [];
      
      tables.forEach((table: any) => {
        originalTableStyles.push(table.style.cssText);
        table.style.overflowX = 'visible';
        table.style.width = 'auto';
      });

      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: "#ffffff",
        windowWidth: element.scrollWidth + 100, // Ensure wide enough for table
      });

      // Restore original styles
      element.style.cssText = originalStyle;
      tables.forEach((table: any, i) => {
        table.style.cssText = originalTableStyles[i];
      });

      const imgData = canvas.toDataURL("image/png");
      
      // Calculate PDF dimensions (A4 landscape)
      const pdf = new jsPDF('l', 'mm', 'a4');
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`prescription_report_${prescriptionData.date || Date.now()}.pdf`);
      
      toast.dismiss();
      toast.success("PDF report downloaded!");
    } catch (error) {
      console.error("Export error:", error);
      toast.dismiss();
      toast.error("Failed to export PDF");
    }
  };

  const handleShareEmail = () => {
    const subject = `Medical Prescription - ${prescriptionData.date}`;
    const medicationsList = prescriptionData.medicines
      .map((m: any) => `- ${m.name}: ${m.quantity} (${m.frequency})`)
      .join("\n");
      
    const body = `Here are my prescription details from ${prescriptionData.date}:\n\n${medicationsList}\n\nNotes: ${prescriptionData.notes}\n\nGenerated by Medical Prescription System.`;
    
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  const handleShareWhatsApp = () => {
    const medicationsList = prescriptionData.medicines
      .map((m: any) => `*${m.name}*: ${m.quantity} (${m.frequency})`)
      .join("\n");
      
    const text = `*Medical Prescription - ${prescriptionData.date}*\n\n${medicationsList}\n\n*Notes*: ${prescriptionData.notes}`;
    
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank");
  };

  return (
    <div className="flex gap-3 justify-center mb-6">
      <Button 
        variant="outline" 
        className="gap-2" 
        onClick={handleExportPDF}
      >
        <Download className="w-4 h-4" />
        Export PDF
      </Button>

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" className="gap-2">
            <Share2 className="w-4 h-4" />
            Share Result
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-48">
          <DropdownMenuItem onClick={handleShareEmail} className="gap-2">
            <Mail className="w-4 h-4" />
            Share via Email
          </DropdownMenuItem>
          <DropdownMenuItem onClick={handleShareWhatsApp} className="gap-2">
            <MessageSquare className="w-4 h-4" />
            Share via WhatsApp
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
};

export default ExportActions;
